# Generated by Django 5.0.14 on 2025-12-04 16:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this workflow.",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional detailed description of what this workflow does.",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
                (
                    "canvas_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="React Flow canvas state (viewport position, zoom, etc.).",
                        verbose_name="Canvas Data",
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this workflow is a reusable template.",
                        verbose_name="Is Template",
                    ),
                ),
                (
                    "last_executed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last execution.",
                        null=True,
                        verbose_name="Last Executed At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["name"], name="workflows_w_name_095c74_idx"),
                    models.Index(
                        fields=["is_template"], name="workflows_w_is_temp_e7a2b1_idx"
                    ),
                    models.Index(
                        fields=["is_active", "-updated_at"],
                        name="workflows_w_is_acti_968646_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("credentials", "API Credentials"),
                            ("rate_limiter", "Rate Limiter"),
                            ("single_address", "Single Address Input"),
                            ("batch_input", "Batch Address Input"),
                            ("transaction_hash", "Transaction Hash Input"),
                            ("chainalysis_cluster_info", "Chainalysis - Cluster Info"),
                            (
                                "chainalysis_cluster_balance",
                                "Chainalysis - Cluster Balance",
                            ),
                            (
                                "chainalysis_cluster_counterparties",
                                "Chainalysis - Counterparties",
                            ),
                            (
                                "chainalysis_transaction_details",
                                "Chainalysis - Transaction Details",
                            ),
                            (
                                "chainalysis_exposure_category",
                                "Chainalysis - Exposure by Category",
                            ),
                            (
                                "chainalysis_exposure_service",
                                "Chainalysis - Exposure by Service",
                            ),
                            ("trm_address_attribution", "TRM - Address Attribution"),
                            ("trm_total_exposure", "TRM - Total Exposure"),
                            ("trm_address_summary", "TRM - Address Summary"),
                            ("trm_address_transfers", "TRM - Address Transfers"),
                            ("trm_network_intelligence", "TRM - Network Intelligence"),
                            ("txt_export", "Export to TXT"),
                            ("excel_export", "Export to Excel"),
                            ("json_export", "Export to JSON"),
                            ("csv_export", "Export to CSV"),
                            ("console_log", "Console Log"),
                        ],
                        help_text="Type identifier for this node.",
                        max_length=100,
                        verbose_name="Node Type",
                    ),
                ),
                (
                    "node_category",
                    models.CharField(
                        choices=[
                            ("configuration", "Configuration"),
                            ("input", "Input"),
                            ("query", "Query"),
                            ("output", "Output"),
                        ],
                        help_text="Category of this node (input, query, output, etc.).",
                        max_length=50,
                        verbose_name="Node Category",
                    ),
                ),
                (
                    "node_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User-customizable display label for this node.",
                        max_length=100,
                        verbose_name="Node Label",
                    ),
                ),
                (
                    "position_x",
                    models.FloatField(
                        default=0.0,
                        help_text="X coordinate on the canvas.",
                        validators=[
                            django.core.validators.MinValueValidator(-10000.0),
                            django.core.validators.MaxValueValidator(10000.0),
                        ],
                        verbose_name="X Position",
                    ),
                ),
                (
                    "position_y",
                    models.FloatField(
                        default=0.0,
                        help_text="Y coordinate on the canvas.",
                        validators=[
                            django.core.validators.MinValueValidator(-10000.0),
                            django.core.validators.MaxValueValidator(10000.0),
                        ],
                        verbose_name="Y Position",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON configuration data for this node.",
                        verbose_name="Node Configuration",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="The workflow this node belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Node",
                "verbose_name_plural": "Nodes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "source_pin",
                    models.CharField(
                        default="output",
                        help_text="The output pin identifier on the source node.",
                        max_length=50,
                        verbose_name="Source Pin",
                    ),
                ),
                (
                    "target_pin",
                    models.CharField(
                        default="input",
                        help_text="The input pin identifier on the target node.",
                        max_length=50,
                        verbose_name="Target Pin",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        help_text="The node where the connection originates.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing",
                        to="workflows.node",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        help_text="The node where the connection terminates.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming",
                        to="workflows.node",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="The workflow this connection belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connection",
                "verbose_name_plural": "Connections",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["workflow", "node_type"], name="workflows_n_workflo_b4e47f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["workflow", "node_category"],
                name="workflows_n_workflo_bd285f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["workflow"], name="workflows_c_workflo_cab47f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["source_node"], name="workflows_c_source__a17d22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["target_node"], name="workflows_c_target__73c374_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.UniqueConstraint(
                fields=("source_node", "target_node", "source_pin", "target_pin"),
                name="unique_connection",
            ),
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.CheckConstraint(
                check=models.Q(("source_node", models.F("target_node")), _negated=True),
                name="no_self_connection",
            ),
        ),
    ]
