# Generated by Django 5.0.14 on 2025-12-04 17:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the workflow (e.g., 'BTC Address Investigation')",
                        max_length=100,
                        verbose_name="Workflow Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of the workflow's purpose",
                        max_length=500,
                        verbose_name="Workflow Description",
                    ),
                ),
                (
                    "canvas_data",
                    models.JSONField(
                        default=dict,
                        help_text="JSON data containing nodes, edges, and viewport state",
                        verbose_name="Canvas Data",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
                "db_table": "workflows",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["name"], name="workflows_name_5bf4ac_idx"),
                    models.Index(
                        fields=["is_active", "-updated_at"],
                        name="workflows_is_acti_8a4b22_idx",
                    ),
                ],
            },
        ),
    ]
