"""Quick test of xhtml2pdf."""
import os
import sys

# Redirect output to file
log_file = open(r'c:\Users\Andy\EasyCall\backend\outputs\test_output.txt', 'w')
sys.stdout = log_file
sys.stderr = log_file

# Add the backend to path
sys.path.insert(0, r'c:\Users\Andy\EasyCall\backend')

# Set up Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
import django
django.setup()

from io import BytesIO
from xhtml2pdf import pisa

html = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Test PDF</title>
    <style>
        body { font-family: Helvetica, Arial, sans-serif; }
        h1 { color: #1a237e; }
        .info { background: #f5f5f5; padding: 15px; }
    </style>
</head>
<body>
    <h1>Test Report</h1>
    <div class="info">
        <p>This is a test PDF generated by xhtml2pdf.</p>
        <p>If you can see this, xhtml2pdf is working correctly!</p>
    </div>
</body>
</html>
"""

output_path = r'c:\Users\Andy\EasyCall\backend\outputs\test_xhtml2pdf.pdf'

# Ensure output directory exists
os.makedirs(os.path.dirname(output_path), exist_ok=True)

print(f"Testing xhtml2pdf...")
print(f"Output path: {output_path}")

try:
    source = BytesIO(html.encode('utf-8'))
    with open(output_path, 'wb') as pdf_file:
        pisa_status = pisa.CreatePDF(source, dest=pdf_file, encoding='utf-8')

    if pisa_status.err:
        print(f"FAILED: {pisa_status.err} errors")
    else:
        print(f"SUCCESS: PDF created at {output_path}")
        print(f"File size: {os.path.getsize(output_path)} bytes")
except Exception as e:
    print(f"ERROR: {e}")
    import traceback
    traceback.print_exc()
finally:
    log_file.flush()
    log_file.close()
