# Generated by Django 5.0.6 on 2025-12-19 14:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable provider name (e.g., 'Chainalysis Reactor').",
                        max_length=100,
                        unique=True,
                        verbose_name="Provider Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (e.g., 'chainalysis').",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Provider description and capabilities.",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Provider status (active, deprecated, inactive).",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="API base URL (e.g., 'https://api.chainalysis.com').",
                        max_length=500,
                        verbose_name="Base URL",
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("api_key", "API Key"),
                            ("bearer_token", "Bearer Token"),
                            ("oauth", "OAuth 2.0"),
                            ("basic_auth", "Basic Authentication"),
                            ("none", "No Authentication"),
                        ],
                        default="api_key",
                        help_text="Authentication method required by this provider.",
                        max_length=20,
                        verbose_name="Authentication Type",
                    ),
                ),
                (
                    "icon_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path to provider icon (optional).",
                        max_length=255,
                        verbose_name="Icon Path",
                    ),
                ),
                (
                    "documentation_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Link to provider API documentation.",
                        max_length=500,
                        verbose_name="Documentation URL",
                    ),
                ),
                (
                    "spec_file_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path to uploaded OpenAPI specification file.",
                        max_length=500,
                        verbose_name="OpenAPI Spec File Path",
                    ),
                ),
                (
                    "spec_format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("openapi_3.0", "OpenAPI 3.0"),
                            ("openapi_3.1", "OpenAPI 3.1"),
                            ("swagger_2.0", "Swagger 2.0"),
                        ],
                        default="",
                        help_text="OpenAPI specification format version.",
                        max_length=20,
                        verbose_name="Spec Format",
                    ),
                ),
                (
                    "spec_parsed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the OpenAPI spec was last parsed.",
                        null=True,
                        verbose_name="Spec Parsed At",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Semantic version (e.g., '1.0.0').",
                        max_length=20,
                        verbose_name="Version",
                    ),
                ),
                (
                    "rate_limit_per_minute",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Default rate limit for this provider (requests per minute).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="Rate Limit (per minute)",
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Default request timeout in seconds.",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name="Timeout (seconds)",
                    ),
                ),
                (
                    "supports_batch",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this provider supports batch requests.",
                        verbose_name="Supports Batch Requests",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional provider-specific configuration (JSON).",
                        verbose_name="Metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Provider",
                "verbose_name_plural": "API Providers",
                "db_table": "providers",
                "ordering": ["-status", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="providers_slug_d85175_idx"),
                    models.Index(
                        fields=["status", "name"], name="providers_status_3ded0f_idx"
                    ),
                    models.Index(
                        fields=["version"], name="providers_version_1b4fbb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="APIEndpoint",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="API endpoint path (e.g., '/clusters/{address}').",
                        max_length=500,
                        verbose_name="Endpoint Path",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                            ("PATCH", "PATCH"),
                        ],
                        help_text="HTTP method (GET, POST, etc.).",
                        max_length=10,
                        verbose_name="HTTP Method",
                    ),
                ),
                (
                    "operation_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="OpenAPI operation ID.",
                        max_length=200,
                        verbose_name="Operation ID",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Brief endpoint description.",
                        max_length=500,
                        verbose_name="Summary",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed endpoint description.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="JSON schema of endpoint parameters (path, query, header).",
                        verbose_name="Parameters",
                    ),
                ),
                (
                    "request_body",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON schema of request body (for POST/PUT).",
                        verbose_name="Request Body",
                    ),
                ),
                (
                    "response_schema",
                    models.JSONField(
                        default=dict,
                        help_text="JSON schema of successful response (200).",
                        verbose_name="Response Schema",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Endpoint tags from OpenAPI spec.",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "requires_auth",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this endpoint requires authentication.",
                        verbose_name="Requires Authentication",
                    ),
                ),
                (
                    "rate_limit_override",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override provider default rate limit (optional).",
                        null=True,
                        verbose_name="Rate Limit Override",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="Provider this endpoint belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Endpoint",
                "verbose_name_plural": "API Endpoints",
                "db_table": "api_endpoints",
                "ordering": ["provider", "path", "method"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedNode",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        db_index=True,
                        help_text="Unique node type identifier (e.g., 'chainalysis_cluster_info').",
                        max_length=100,
                        unique=True,
                        verbose_name="Node Type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("configuration", "Configuration"),
                            ("input", "Input"),
                            ("query", "Query"),
                            ("output", "Output"),
                        ],
                        help_text="Node category (configuration, input, query, output).",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable node name shown in UI.",
                        max_length=100,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Node description for users.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "input_pins",
                    models.JSONField(
                        default=list,
                        help_text="Array of input pin definitions (JSON).",
                        verbose_name="Input Pins",
                    ),
                ),
                (
                    "output_pins",
                    models.JSONField(
                        default=list,
                        help_text="Array of output pin definitions (JSON).",
                        verbose_name="Output Pins",
                    ),
                ),
                (
                    "configuration_fields",
                    models.JSONField(
                        default=list,
                        help_text="Array of configuration field definitions (JSON).",
                        verbose_name="Configuration Fields",
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        default=dict,
                        help_text="Validation rules for inputs and configuration (JSON).",
                        verbose_name="Validation Rules",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🔌",
                        help_text="Emoji or icon identifier for node.",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#00897b",
                        help_text="Hex color code for node background.",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional node-specific metadata (JSON).",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        help_text="API endpoint this node calls (null for credential nodes).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="providers.apiendpoint",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="Provider this node belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_nodes",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Node",
                "verbose_name_plural": "Generated Nodes",
                "db_table": "generated_nodes",
                "ordering": ["provider", "category", "display_name"],
                "indexes": [
                    models.Index(
                        fields=["node_type"], name="generated_n_node_ty_ab1e80_idx"
                    ),
                    models.Index(
                        fields=["provider", "category"],
                        name="generated_n_provide_77c92f_idx",
                    ),
                    models.Index(
                        fields=["category"], name="generated_n_categor_38c802_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="apiendpoint",
            index=models.Index(
                fields=["provider", "path"], name="api_endpoin_provide_db8648_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiendpoint",
            index=models.Index(fields=["method"], name="api_endpoin_method_b98dc7_idx"),
        ),
        migrations.AddIndex(
            model_name="apiendpoint",
            index=models.Index(
                fields=["operation_id"], name="api_endpoin_operati_8d3c61_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="apiendpoint",
            constraint=models.UniqueConstraint(
                fields=("provider", "path", "method"),
                name="unique_endpoint_per_provider",
            ),
        ),
    ]
