# Generated by Django 5.0.6 on 2025-12-19 13:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIEndpoint",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text='URL path (e.g., "/v2/entities/{address}")',
                        max_length=1000,
                        verbose_name="Path",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        default="GET",
                        help_text="HTTP method for this endpoint",
                        max_length=10,
                        verbose_name="HTTP Method",
                    ),
                ),
                (
                    "operation_id",
                    models.CharField(
                        help_text="Unique operation identifier from OpenAPI spec",
                        max_length=200,
                        verbose_name="Operation ID",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short description of what this endpoint does",
                        max_length=200,
                        verbose_name="Summary",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of the endpoint",
                        verbose_name="Description",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of parameter definitions from OpenAPI spec",
                        verbose_name="Parameters",
                    ),
                ),
                (
                    "request_body",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Request body schema (for POST/PUT/PATCH)",
                        null=True,
                        verbose_name="Request Body",
                    ),
                ),
                (
                    "responses",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Response schemas mapped by status code",
                        verbose_name="Responses",
                    ),
                ),
                (
                    "deprecated",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this endpoint is deprecated",
                        verbose_name="Deprecated",
                    ),
                ),
                (
                    "requires_auth",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this endpoint requires authentication",
                        verbose_name="Requires Authentication",
                    ),
                ),
                (
                    "rate_limit_override",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional custom rate limit for this specific endpoint",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="Rate Limit Override",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of tags for categorization",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Endpoint",
                "verbose_name_plural": "API Endpoints",
                "db_table": "api_endpoints",
                "ordering": ["provider", "path", "method"],
            },
        ),
        migrations.CreateModel(
            name="ProviderVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text='Version string (e.g., "2.1.0")',
                        max_length=20,
                        verbose_name="Version",
                    ),
                ),
                (
                    "spec_file_path",
                    models.CharField(
                        help_text="Path to the OpenAPI specification file for this version",
                        max_length=1000,
                        verbose_name="Spec File Path",
                    ),
                ),
                (
                    "changelog",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable description of changes in this version",
                        verbose_name="Changelog",
                    ),
                ),
                (
                    "breaking_changes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of breaking changes introduced in this version",
                        verbose_name="Breaking Changes",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this is the currently active version",
                        verbose_name="Is Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Version",
                "verbose_name_plural": "Provider Versions",
                "db_table": "provider_versions",
                "ordering": ["provider", "-version"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedNode",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        db_index=True,
                        help_text='Unique identifier for this node type (e.g., "chainalysis_entity_lookup")',
                        max_length=100,
                        unique=True,
                        verbose_name="Node Type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("configuration", "Configuration"),
                            ("input", "Input"),
                            ("query", "Query"),
                            ("output", "Output"),
                        ],
                        db_index=True,
                        default="query",
                        help_text="Node category determines where it appears in the palette",
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name shown in the node palette",
                        max_length=200,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description shown in the node palette",
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="api",
                        help_text="Icon name or path for visual representation",
                        max_length=100,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#4CAF50",
                        help_text='Hex color code for node styling (e.g., "#4CAF50")',
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                (
                    "input_pins",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of input pin definitions",
                        verbose_name="Input Pins",
                    ),
                ),
                (
                    "output_pins",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of output pin definitions",
                        verbose_name="Output Pins",
                    ),
                ),
                (
                    "config_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON schema for node configuration panel",
                        verbose_name="Configuration Schema",
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Validation rules for pin values",
                        verbose_name="Validation Rules",
                    ),
                ),
                (
                    "default_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default values for pins and configuration",
                        verbose_name="Default Values",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        help_text="The API endpoint this node was generated from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_nodes",
                        to="providers.apiendpoint",
                        verbose_name="API Endpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Node",
                "verbose_name_plural": "Generated Nodes",
                "db_table": "generated_nodes",
                "ordering": ["category", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Human-readable name (e.g., "Chainalysis Reactor")',
                        max_length=100,
                        verbose_name="Provider Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='URL-safe identifier (e.g., "chainalysis-reactor")',
                        max_length=100,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the provider and its capabilities",
                        verbose_name="Description",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text='Base URL for API requests (e.g., "https://api.chainalysis.com")',
                        max_length=500,
                        verbose_name="Base URL",
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "No Authentication"),
                            ("api_key", "API Key"),
                            ("bearer", "Bearer Token"),
                            ("oauth2", "OAuth 2.0"),
                            ("basic", "Basic Authentication"),
                        ],
                        default="api_key",
                        help_text="Type of authentication required by this provider",
                        max_length=20,
                        verbose_name="Authentication Type",
                    ),
                ),
                (
                    "icon_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to icon file (relative to media root)",
                        max_length=1000,
                        null=True,
                        verbose_name="Icon Path",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Current lifecycle status of this provider",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0",
                        help_text='Current API version (e.g., "2.1.0")',
                        max_length=20,
                        verbose_name="Version",
                    ),
                ),
                (
                    "spec_file_path",
                    models.CharField(
                        help_text="Path to the OpenAPI specification file",
                        max_length=1000,
                        verbose_name="OpenAPI Spec File Path",
                    ),
                ),
                (
                    "rate_limit",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Maximum requests per minute (1-10000)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="Rate Limit",
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Request timeout in seconds (5-300)",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name="Timeout",
                    ),
                ),
                (
                    "requires_paid_key",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this provider requires a paid API key",
                        verbose_name="Requires Paid Key",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional provider-specific configuration",
                        verbose_name="Metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "db_table": "providers",
                "ordering": ["name", "-version"],
                "indexes": [
                    models.Index(
                        fields=["slug", "version"], name="provider_slug_version_idx"
                    ),
                    models.Index(fields=["status"], name="provider_status_idx"),
                    models.Index(fields=["-created_at"], name="provider_created_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="provider",
            constraint=models.UniqueConstraint(
                fields=("slug", "version"), name="unique_provider_slug_version"
            ),
        ),
        migrations.AddField(
            model_name="generatednode",
            name="provider",
            field=models.ForeignKey(
                help_text="The provider this node belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_nodes",
                to="providers.provider",
                verbose_name="Provider",
            ),
        ),
        migrations.AddField(
            model_name="apiendpoint",
            name="provider",
            field=models.ForeignKey(
                help_text="The provider this endpoint belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="endpoints",
                to="providers.provider",
                verbose_name="Provider",
            ),
        ),
        migrations.AddField(
            model_name="providerversion",
            name="provider",
            field=models.ForeignKey(
                help_text="The provider this version belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="providers.provider",
                verbose_name="Provider",
            ),
        ),
        migrations.AddIndex(
            model_name="generatednode",
            index=models.Index(fields=["node_type"], name="node_node_type_idx"),
        ),
        migrations.AddIndex(
            model_name="generatednode",
            index=models.Index(fields=["category"], name="node_category_idx"),
        ),
        migrations.AddIndex(
            model_name="generatednode",
            index=models.Index(fields=["provider"], name="node_provider_idx"),
        ),
        migrations.AddIndex(
            model_name="apiendpoint",
            index=models.Index(
                fields=["provider", "path", "method"], name="endpoint_provider_path_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiendpoint",
            index=models.Index(fields=["deprecated"], name="endpoint_deprecated_idx"),
        ),
        migrations.AddIndex(
            model_name="apiendpoint",
            index=models.Index(
                fields=["operation_id"], name="endpoint_operation_id_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="apiendpoint",
            constraint=models.UniqueConstraint(
                fields=("provider", "path", "method"),
                name="unique_endpoint_per_provider",
            ),
        ),
        migrations.AddIndex(
            model_name="providerversion",
            index=models.Index(
                fields=["provider", "version"], name="version_provider_ver_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerversion",
            index=models.Index(fields=["is_active"], name="version_is_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="providerversion",
            constraint=models.UniqueConstraint(
                fields=("provider", "version"), name="unique_provider_version"
            ),
        ),
    ]
