# Generated by Django 5.0.14 on 2025-12-04 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("paused", "Paused"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current execution status",
                        max_length=20,
                        verbose_name="Execution Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When execution started",
                        null=True,
                        verbose_name="Started At",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When execution completed",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if execution failed",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        default=dict,
                        help_text="Aggregated results from all nodes",
                        verbose_name="Result",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="The workflow that was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execution Log",
                "verbose_name_plural": "Execution Logs",
                "db_table": "execution_logs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow", "-started_at"],
                        name="execution_l_workflo_324e71_idx",
                    ),
                    models.Index(
                        fields=["status", "-started_at"],
                        name="execution_l_status_5f279a_idx",
                    ),
                ],
            },
        ),
    ]
