# Generated by Django 5.0.14 on 2025-12-04 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Execution",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("paused", "Paused"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current execution status.",
                        max_length=50,
                        verbose_name="Execution Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When execution started.",
                        null=True,
                        verbose_name="Started At",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When execution completed.",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Total execution time in seconds.",
                        null=True,
                        verbose_name="Duration",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if execution failed.",
                        max_length=1000,
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON data containing execution results.",
                        verbose_name="Result Data",
                    ),
                ),
                (
                    "executed_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Identifier for who/what triggered the execution.",
                        max_length=100,
                        verbose_name="Executed By",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="The workflow being executed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execution",
                "verbose_name_plural": "Executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        help_text="Log level.",
                        max_length=20,
                        verbose_name="Log Level",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="The log message.",
                        max_length=100000,
                        verbose_name="Log Message",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional JSON metadata.",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        help_text="The execution this log belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="execution.execution",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional node that generated the log.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_logs",
                        to="workflows.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execution Log",
                "verbose_name_plural": "Execution Logs",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="NodeExecutionResult",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Execution status for this node.",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When node execution started.",
                        null=True,
                        verbose_name="Started At",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When node execution completed.",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Node execution time in seconds.",
                        null=True,
                        verbose_name="Duration (seconds)",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON data received as input.",
                        verbose_name="Input Data",
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON data produced as output.",
                        verbose_name="Output Data",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if node failed.",
                        max_length=1000,
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        help_text="The parent execution.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_results",
                        to="execution.execution",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        help_text="The node that was executed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_results",
                        to="workflows.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "Node Execution Result",
                "verbose_name_plural": "Node Execution Results",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="execution",
            index=models.Index(
                fields=["workflow", "status"], name="execution_e_workflo_c283e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="execution",
            index=models.Index(
                fields=["status", "-created_at"], name="execution_e_status_2b8c30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="execution",
            index=models.Index(
                fields=["-started_at"], name="execution_e_started_c7e652_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="executionlog",
            index=models.Index(
                fields=["execution", "level"], name="execution_e_executi_49ba99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="executionlog",
            index=models.Index(
                fields=["execution", "created_at"],
                name="execution_e_executi_b4741d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="executionlog",
            index=models.Index(fields=["node"], name="execution_e_node_id_a88216_idx"),
        ),
        migrations.AddIndex(
            model_name="nodeexecutionresult",
            index=models.Index(
                fields=["execution", "node"], name="execution_n_executi_20b094_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nodeexecutionresult",
            index=models.Index(
                fields=["execution", "status"], name="execution_n_executi_5a694d_idx"
            ),
        ),
    ]
