# Generated by Django 5.0.6 on 2025-12-19 15:41

import fields.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0002_alter_executionlog_result_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executionlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("paused", "Paused"),
                ],
                db_index=True,
                default=fields.choices.ExecutionStatus["PENDING"],
                help_text="Current execution status",
                max_length=20,
                verbose_name="Execution Status",
            ),
        ),
    ]
