openapi: 3.0.0
info:
  title: Etherscan Account API - ERC20 Token Holding
  version: 2.0.0
  description: Retrieves ERC-20 token balances for an address

servers:
  - url: https://api.etherscan.io/v2

paths:
  /api:
    get:
      summary: Get Address ERC20 Token Holding
      operationId: getAddressTokenBalance
      tags:
        - Account
        - ERC20
      
      parameters:
        - name: chainid
          in: query
          required: false
          description: Chain ID to query
          schema:
            type: string
            default: "1"
        
        - name: module
          in: query
          required: true
          description: Module name
          schema:
            type: string
            default: account
            enum:
              - account
        
        - name: action
          in: query
          required: true
          description: Action name
          schema:
            type: string
            default: addresstokenbalance
            enum:
              - addresstokenbalance
        
        - name: address
          in: query
          required: true
          description: Ethereum address to check
          schema:
            type: string
            pattern: '^0x[a-fA-F0-9]{40}$'
        
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 10000
            default: 100
        
        - name: apikey
          in: query
          required: true
          description: Etherscan API key
          schema:
            type: string

      responses:
        '200':
          description: Token holdings retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        TokenAddress:
                          type: string
                        TokenName:
                          type: string
                        TokenSymbol:
                          type: string
                        TokenQuantity:
                          type: string
                        TokenDivisor:
                          type: string
                        TokenPriceUSD:
                          type: string
