# Generated by Django 5.0.14 on 2025-12-04 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "batch_size_limit",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Maximum addresses per batch (max: 10000).",
                        verbose_name="Batch Size Limit",
                    ),
                ),
                (
                    "execution_timeout",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="Default workflow timeout in seconds.",
                        verbose_name="Execution Timeout",
                    ),
                ),
                (
                    "chainalysis_rate_limit",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Requests per minute for Chainalysis API.",
                        verbose_name="Chainalysis Rate Limit",
                    ),
                ),
                (
                    "trm_rate_limit",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Requests per minute for TRM Labs API.",
                        verbose_name="TRM Labs Rate Limit",
                    ),
                ),
                (
                    "default_blockchain",
                    models.CharField(
                        default="bitcoin",
                        help_text="Default blockchain for new input nodes.",
                        max_length=50,
                        verbose_name="Default Blockchain",
                    ),
                ),
                (
                    "enable_detailed_logging",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to log detailed execution information.",
                        verbose_name="Enable Detailed Logging",
                    ),
                ),
                (
                    "enable_websocket_logs",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to send logs via WebSocket in real-time.",
                        verbose_name="Enable WebSocket Logs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Global Settings",
                "verbose_name_plural": "Global Settings",
            },
        ),
        migrations.CreateModel(
            name="APICredential",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("chainalysis", "Chainalysis Reactor"),
                            ("trm_labs", "TRM Labs"),
                        ],
                        db_index=True,
                        help_text="API provider (chainalysis, trm_labs).",
                        max_length=50,
                        verbose_name="API Provider",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="Default",
                        help_text="Human-readable label for this credential set.",
                        max_length=100,
                        verbose_name="Label",
                    ),
                ),
                (
                    "api_key_encrypted",
                    models.CharField(
                        help_text="Encrypted API key.",
                        max_length=512,
                        verbose_name="API Key (Encrypted)",
                    ),
                ),
                (
                    "api_secret_encrypted",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Encrypted API secret (if applicable).",
                        max_length=512,
                        verbose_name="API Secret (Encrypted)",
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Base URL for the API (leave empty for default).",
                        max_length=500,
                        verbose_name="API URL",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default credential for the provider.",
                        verbose_name="Is Default",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When these credentials were last used.",
                        null=True,
                        verbose_name="Last Used At",
                    ),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When these credentials were last verified.",
                        null=True,
                        verbose_name="Last Verified At",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether these credentials have been verified.",
                        verbose_name="Is Verified",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Credential",
                "verbose_name_plural": "API Credentials",
                "ordering": ["-is_default", "provider", "label"],
                "indexes": [
                    models.Index(
                        fields=["provider", "is_default"],
                        name="settings_ma_provide_a5b013_idx",
                    ),
                    models.Index(
                        fields=["provider", "is_active"],
                        name="settings_ma_provide_f4e5d9_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="apicredential",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_default", True)),
                fields=("provider",),
                name="unique_default_per_provider",
            ),
        ),
    ]
