# Generated by Django 5.0.6 on 2025-12-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicredential",
            name="api_key_encrypted",
            field=models.CharField(
                help_text="Encrypted API key.",
                max_length=510,
                verbose_name="API Key (Encrypted)",
            ),
        ),
        migrations.AlterField(
            model_name="apicredential",
            name="api_secret_encrypted",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Encrypted API secret (if applicable).",
                max_length=510,
                verbose_name="API Secret (Encrypted)",
            ),
        ),
        migrations.AlterField(
            model_name="apicredential",
            name="provider",
            field=models.CharField(
                choices=[("chainalysis", "Chainalysis"), ("trm_labs", "TRM Labs")],
                db_index=True,
                help_text="API provider (chainalysis, trm_labs).",
                max_length=50,
                verbose_name="API Provider",
            ),
        ),
    ]
