# Generated by Django 5.0.6 on 2025-12-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_manager", "0002_alter_apicredential_api_key_encrypted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicredential",
            name="provider",
            field=models.CharField(
                choices=[
                    ("chainalysis", "Chainalysis Reactor"),
                    ("trm_labs", "TRM Labs"),
                ],
                db_index=True,
                help_text="API provider (chainalysis, trm_labs).",
                max_length=50,
                verbose_name="API Provider",
            ),
        ),
    ]
