# Generated by Django 5.0.6 on 2025-12-19 15:31

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpenAPISpec",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this record is active.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("chainalysis", "Chainalysis Reactor"),
                            ("trm_labs", "TRM Labs"),
                            ("custom", "Custom Provider"),
                        ],
                        db_index=True,
                        help_text="The API provider this specification is for",
                        max_length=50,
                        verbose_name="API Provider",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this API specification",
                        max_length=100,
                        verbose_name="Api Provider Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of this specification",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="API version (e.g., '1.0', 'v2')",
                        max_length=50,
                        verbose_name="Api Version",
                    ),
                ),
                (
                    "spec_file",
                    models.FileField(
                        help_text="OpenAPI specification file (YAML or JSON)",
                        upload_to="api_specs/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["yaml", "yml", "json"]
                            )
                        ],
                        verbose_name="Spec File",
                    ),
                ),
                (
                    "parsed_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed endpoint data from the specification",
                        verbose_name="Parsed Endpoints",
                    ),
                ),
                (
                    "is_parsed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the spec has been successfully parsed",
                        verbose_name="Is Parsed",
                    ),
                ),
                (
                    "parse_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if parsing failed",
                        verbose_name="Parse Error",
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenAPI Specification",
                "verbose_name_plural": "OpenAPI Specifications",
                "db_table": "api_specs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "-created_at"],
                        name="api_specs_provide_0065cf_idx",
                    ),
                    models.Index(
                        fields=["is_parsed", "-created_at"],
                        name="api_specs_is_pars_ff18af_idx",
                    ),
                ],
                "unique_together": {("provider", "version")},
            },
        ),
    ]
