# Generated by Django 5.0.6 on 2025-12-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openapispec",
            name="provider",
            field=models.CharField(
                db_index=True,
                help_text="The API provider this specification is for",
                max_length=50,
                verbose_name="API Provider",
            ),
        ),
    ]
