# Generated by Django 5.0.6 on 2025-12-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_alter_openapispec_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openapispec",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name for this API specification",
                max_length=100,
                verbose_name="Api Provider Name",
            ),
        ),
        migrations.AlterField(
            model_name="openapispec",
            name="version",
            field=models.CharField(
                blank=True,
                default="1.0.0",
                help_text="API version (e.g., '1.0', 'v2')",
                max_length=50,
                verbose_name="Api Version",
            ),
        ),
    ]
