# Generated by Django 5.0.6 on 2025-12-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_alter_openapispec_name_alter_openapispec_version"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="openapispec",
            unique_together=set(),
        ),
    ]
